name: bernardyn
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.14
  - numpy>=2
  - h5py>=3
  - pyside6
  - pyqtgraph
  - pyopengl>=3.1.7
  - pip
  - pip:
      - "pyirena[qtplot]>=1.1.0b12,<2"
      - -e .
